name: dask-kubernetes-test
channels:
  - defaults
  - conda-forge
dependencies:
  - flake8
  - ipywidgets
  - dask=1.2.0
  - nomkl
  - pytest
  - black
  - python=3.6
  - pyyaml
  - pip:
    - kubernetes==9
    - kubernetes-asyncio
    - pytest-asyncio
    - git+https://github.com/tornadoweb/tornado@975e9168560cc03f6210d0d3aab10c870bd47080
